### ISSUE TITLE
How to create my name on that gif? 

### ISSUE THREAD

**Issue by namnaku87** [Hardly-Human/Hardly-Human#1]
I need your help in creating my name on that gif which you using right now. can you guide me on that. Thanks.

**Comment by Hardly-Human** [comment]
I have used [https://msgif.net](https://msgif.net)
  options => screen-size : Twitter
                     design style : Neon

**Comment by namnaku87** [comment]
Hey, by the way your portfolio website looking absolutely stunning. Keep up the great work!

How did you get the idea to create your portfolio website? Also, do you have any other portfolio templates?

Thankyou.

**Comment by Hardly-Human** [comment]
Start with a template and customize it as you like.
I have used some templates from here for inspiration:
[https://themeforest.net/](https://themeforest.net/)
[https://themewagon.com/](https://themewagon.com/)

**Comment by namnaku87** [comment]
> Start with a template and customize it as you like. I have used some templates from here for inspiration: https://themeforest.net/ https://themewagon.com/

Thanks dude that really helped me a lot.
